### ISSUE TITLE
v0.7.0 Release

### ISSUE THREAD

**Issue by DivineDominion** [ReSwift/ReSwift-Router#117]
We have a breaking change already on master, removing the action creator stuff. 

- [x] #111 Change SwiftPM target type
- [x] #115 Update for Swift 5
- [x] #116 rename methods for "modern" conventions (i.e. according to the last 3 years of practice :))
- [x] increase version number, of course
- [x] push to CocoaPods
- [x] update to ReSwift 5

Anything else that comes to mind, folks?
